openapi: 3.0.0
info:
  title: Order Service API
  description: API documentation for the Order Service.
  version: 1.0.0
tags:
  - name: Order
  - name: OrderItem
  - name: OrderStatusHistory
paths: {}
