openapi: 3.0.0
info:
  title: User Service API
  description: API documentation for the User Service.
  version: 1.0.0
tags:
  - name: Auth
  - name: Users
  - name: Code
  - name: Loyalty
  - name: Address
paths: {}
